import Foundation
import LedgerTargetCore
import LedgerTargetAppModel

// Offline pipe adapter for import tooling. No file paths, network, credentials
// or database access; callers retain original and generated bytes durably.
struct Input: Decodable {
    let accountId: String
    let attachmentId: String
    let sha256: String
    let byteCount: String
    let mediaType: String
    let storagePath: String
    let base64: String
}
struct Output: Encodable {
    let recipe: String
    let sha256: String
    let byteCount: String
    let mediaType: String
    let width: Int
    let height: Int
    let base64: String
}
do {
    guard CommandLine.arguments.count == 1 else { throw DownloadedItemImageFailure.malformed }
    var inputBytes = Data()
    let limit = Int(ItemCardThumbnailGenerator.maximumSourceBytes) * 4 / 3 + 16_384
    while let chunk = try FileHandle.standardInput.read(upToCount: 65_536), !chunk.isEmpty {
        guard inputBytes.count <= limit - chunk.count else { throw ItemCardThumbnailGenerationFailure.sourceTooLarge }
        inputBytes.append(chunk)
    }
    let input = try JSONDecoder().decode(Input.self,from: inputBytes)
    guard let originalBytes = Data(base64Encoded: input.base64) else { throw DownloadedItemImageFailure.malformed }
    let original = try DownloadedImageObjectReference(accountId: .init(validating: input.accountId),
        attachmentId: input.attachmentId,sha256: input.sha256,byteCount: input.byteCount,
        mediaType: input.mediaType,storagePath: input.storagePath)
    let generated = try ItemCardThumbnailGenerator.generate(originalBytes: originalBytes,expectedOriginal: original)
    let result = Output(recipe: generated.recipe,sha256: generated.contentSHA256.rawValue,
        byteCount: String(generated.byteCount),mediaType: generated.mediaType,
        width: generated.width,height: generated.height,base64: generated.bytes.base64EncodedString())
    try FileHandle.standardOutput.write(contentsOf: JSONEncoder().encode(result))
} catch {
    // Do not echo source data or caller-provided metadata in diagnostics.
    try? FileHandle.standardError.write(contentsOf: Data("Thumbnail generation rejected input.\n".utf8))
    exit(1)
}
