const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {planMediaReferences,planSpaceMedia,spacePublicationSQL,planSpaceDetails,spaceDetailsPublicationSQL,planTransactionMedia,transactionPublicationSQL,planExpenseReceipts}=require('../real-copy-transaction-media.cjs');
const transaction='realcopy-b9d236394770-transaction-'+crypto.createHash('sha256').update('one').digest('hex').slice(0,24);
const ids=new Set([transaction]);
const ref=(object,kind='image')=>({mapValue:{fields:{url:{stringValue:'https://firebasestorage.googleapis.com/v0/b/ledger-nine4.firebasestorage.app/o/'+object},kind:{stringValue:kind}}}});
const source=fields=>({account:'accounts/test',documents:[{name:'accounts/test/transactions/one',fields}]});
const array=values=>({arrayValue:{values}});
const copies=new Map(['image','pdf'].map(object=>[object,{object,contentType:object==='pdf'?'application/pdf':'image/jpeg',bytes:10,sha256:'a'.repeat(64),file:object}]));
test('Space details preserve source dates and notes, require explicit checklist handling, and reject conflicting replay',()=>{
  const space=transaction.replace('-transaction-','-space-');
  const doc={name:'accounts/test/spaces/one',createTime:'2025-01-01T00:00:00.123456Z',updateTime:'2025-01-03T00:00:00Z',
    fields:{notes:{stringValue:" Owner's note "},createdAt:{timestampValue:'2025-01-02T00:00:00Z'}}};
  const snapshot={account:'accounts/test',documents:[doc,{...doc,name:'accounts/foreign/spaces/one'}]};
  const plan=planSpaceDetails(snapshot,new Set([space]));
  assert.equal(plan.length,1);assert.equal(plan[0].notes,"Owner's note");
  assert.equal(plan[0].created.source,'createdAt');assert.equal(plan[0].created.milliseconds,Date.parse('2025-01-02T00:00:00Z'));
  assert.equal(plan[0].updated.source,'updateTime');
  const sql=spaceDetailsPublicationSQL(plan,'upload-http-owner-test');
  assert.match(sql,/Owner''s note/);assert.match(sql,/Existing Space detail differs/);assert.match(sql,/QA access changed/);
  assert.match(sql,/Existing Space checklists need review/);assert.match(sql,/on conflict\(id\) do nothing/);
  assert.throws(()=>spaceDetailsPublicationSQL(plan,'foreign-owner'));
  doc.fields.createdAt={nullValue:null};
  assert.equal(planSpaceDetails(snapshot,new Set([space]))[0].created.milliseconds,Date.parse('2025-01-01T00:00:00.123Z'));
  doc.fields.checklists=array([{mapValue:{fields:{}}}]);
  assert.throws(()=>planSpaceDetails(snapshot,new Set([space])),/checklists require conversion/);
  doc.fields.checklists={nullValue:null};
  doc.fields.createdAt={timestampValue:'2025-02-30T00:00:00Z'};
  assert.throws(()=>planSpaceDetails(snapshot,new Set([space])),/Invalid Space timestamp/);
  doc.fields.createdAt={nullValue:null};delete doc.createTime;
  assert.throws(()=>planSpaceDetails(snapshot,new Set([space])),/timestamp evidence/);
  assert.throws(()=>planSpaceDetails({account:'accounts/test',documents:[]},new Set([space])),/Incomplete Space detail/);
});
test('Space planning preserves mixed media and refuses partial galleries',()=>{
  const space=transaction.replace('-transaction-','-space-');
  const input={account:'accounts/test',documents:[{name:'accounts/test/spaces/one',fields:{images:array([ref('image'),ref('pdf','pdf')])}}]};
  const planned=planSpaceMedia(input,copies,new Set([space]));
  assert.equal(planned.spaces.length,1);
  assert.deepEqual(planned.spaces[0].images.map(image=>image.contentType),['image/jpeg','application/pdf']);
  assert.equal(planned.spaces[0].primaryIndex,0);
  assert.equal(planned.objects.size,2);
  for(const image of planned.objects.values()) image.storagePath=`accounts/realcopy-b9d236394770-account/attachments/${image.id}/${image.sha256}`;
  const sql=spacePublicationSQL(planned,'upload-http-owner-test');
  assert.match(sql,/insert into public.space_media_sets/);
  assert.match(sql,/Existing Space gallery differs/);
  assert.match(sql,/Existing Space reference differs/);
  assert.match(sql,/set constraints all immediate/);
  assert.equal(spacePublicationSQL(planned,'upload-http-owner-test'),sql);
  assert.throws(()=>spacePublicationSQL(planned,'foreign-owner'));
  assert.equal(planSpaceMedia(input,copies,new Set()).spaces.length,0);
  const missing=planSpaceMedia(input,new Map([['image',copies.get('image')]]),new Set([space]));
  assert.equal(missing.spaces.length,0);
  assert.equal(missing.objects.size,0);
  assert.equal(missing.blocked[0].reason,'original_not_copied');
  input.documents[0].fields.images=array([]);
  assert.equal(planSpaceMedia(input,copies,new Set([space])).spaces[0].images.length,0);
});
test('shared receipt planning retains exact reference evidence and refuses partial mappings',()=>{
  const references=[ref('pdf','pdf'),ref('image')];
  references[0].mapValue.fields.fileName={stringValue:'Original receipt.pdf'};
  const plan=planMediaReferences(array(references),copies,'receipts');
  assert.deepEqual(plan.images.map(x=>x.sourceReference),references);
  assert.equal(plan.images[0].fileName,'Original receipt.pdf');
  assert.equal(planMediaReferences(array([...references,ref('missing')]),copies,'receipts').images,undefined);
  assert.equal(planMediaReferences({arrayValue:{values:{bad:true}}},copies,'receipts').reason,'invalid_section');
});
test('Expense receipts share validation but bind object IDs to the selected QA Account',()=>{
  const snapshot=source({receiptImages:array([ref('pdf','pdf'),ref('image')])});
  const account='realcopy-b9d236394770-check-0123456789ab-account';
  const plan=planExpenseReceipts(snapshot,copies,account,['one']);
  assert.equal(plan.blocked.length,0);
  assert.deepEqual(plan.receipts[0].images.map(x=>x.object),['pdf','image']);
  for(const image of plan.objects.values()) assert.equal(image.storagePath,`accounts/${account}/attachments/${image.id}/${image.sha256}`);
  assert.equal(planExpenseReceipts(snapshot,copies,account,[]).objects.size,0);
  assert.throws(()=>planExpenseReceipts(snapshot,copies,'foreign-account',['one']),/Unapproved/);
  assert.throws(()=>planExpenseReceipts(snapshot,copies,account,['missing']),/Missing/);
  const missing=planExpenseReceipts(snapshot,new Map(),account,['one']);
  assert.equal(missing.objects.size,0);assert.equal(missing.receipts.length,0);
  assert.equal(missing.blocked[0].reason,'original_not_copied');
});
test('only imported Transactions; image/PDF receipt order and empty other section preserved',()=>{
  const s=source({receiptImages:array([ref('pdf','pdf'),ref('image')])});
  assert.equal(planTransactionMedia(s,copies,new Set()).sections.length,0);
  const plan=planTransactionMedia(s,copies,ids);
  assert.equal(plan.sections.length,2);assert.equal(plan.blocked.length,0);
  assert.deepEqual(plan.sections[0].images.map(x=>x.object),['pdf','image']);
  assert.equal(plan.sections[1].images.length,0);
  for(const image of plan.objects.values()) image.storagePath=`accounts/realcopy-b9d236394770-account/attachments/${image.id}/${image.sha256}`;
  const sql=transactionPublicationSQL(plan,'upload-http-owner-test');
  assert.match(sql,/QA access changed/);assert.match(sql,/Existing Transaction attachment differs/);
  assert.match(sql,/file_name is not distinct from null/);assert.match(sql,/set constraints all immediate;/);
  assert.ok(!sql.includes('do $ begin'));assert.match(sql,/do \$\$ begin/);
});
test('unavailable, duplicate, malformed and unsupported sections never publish partial contents',()=>{
  for(const values of [[ref('image'),ref('missing')],[ref('image'),ref('image')],[ref('pdf','file')]]){
    const plan=planTransactionMedia(source({receiptImages:array(values)}),copies,ids);
    assert.equal(plan.blocked.length,1);assert.equal(plan.sections[0].section,'other');assert.equal(plan.objects.size,0);
  }
  assert.equal(planTransactionMedia(source({receiptImages:{stringValue:'bad'}}),copies,ids).blocked.length,1);
  assert.equal(planTransactionMedia(source({otherImages:array([ref('pdf','pdf')])}),copies,ids).blocked.length,1);
  assert.equal(planTransactionMedia(source({transactionImages:array([ref('image')])}),copies,ids).sections.length,0);
});
