-- Generated by local db pull/migra. Review retains invoker/SELECT grants and
-- excludes local-only replication-role grants; no stored history/category copy.
create or replace view "ledger_private"."transaction_current_item_categories" with (security_invoker=true) as SELECT id,
    account_id,
    COALESCE(( SELECT jsonb_agg(jsonb_build_object('itemId', p.item_id, 'placementId', p.id, 'categoryId', c.id) ORDER BY (p.item_id COLLATE "C")) AS jsonb_agg
           FROM ((public.spike_item_placements p
             LEFT JOIN public.spike_item_project_categories a ON (((a.account_id = p.account_id) AND (a.id = p.id) AND (a.item_id = p.item_id) AND (a.project_id = p.project_id))))
             LEFT JOIN public.spike_budget_categories c ON (((c.account_id = a.account_id) AND (c.id = a.category_id))))
          WHERE ((t.scope_kind = 'project'::text) AND (p.account_id = t.account_id) AND (p.project_id = t.project_id) AND (p.scope_kind = 'project'::text) AND (p.ended_at IS NULL) AND (((t.origin = 'vendor_payment'::text) AND (EXISTS ( SELECT 1
                   FROM public.transaction_receipt_items r
                  WHERE ((r.account_id = t.account_id) AND (r.transaction_id = t.id) AND (r.item_id = p.item_id) AND (r.membership_kind = 'linked'::text))))) OR ((t.origin = 'firebase_client_payment'::text) AND (EXISTS ( SELECT 1
                   FROM ledger_private.item_client_payment_connections link
                  WHERE ((link.account_id = t.account_id) AND (link.transaction_id = t.id) AND (link.item_id = p.item_id) AND (link.placement_id = p.id) AND (link.project_id = t.project_id) AND (link.client_id = t.client_id) AND (link.transaction_type = t.type) AND (link.transaction_role = t.role) AND (link.ended_at IS NULL)))))))), '[]'::jsonb) AS items
   FROM public.spike_transactions t;


revoke all on ledger_private.transaction_current_item_categories from public,anon,authenticated,service_role;
grant select on ledger_private.transaction_current_item_categories to authenticated;

create or replace view "ledger_private"."transaction_display" with (security_invoker=true) as SELECT t.id,
    t.account_id,
    t.scope_kind,
    t.project_id,
    t.client_id,
    jsonb_build_object('accountId', t.account_id, 'principalId', ledger_private.current_principal_id(), 'transactionId', t.id, 'scopeKind', t.scope_kind, 'projectId', t.project_id, 'clientId', t.client_id, 'type', t.type, 'role', t.role, 'origin', t.origin, 'amountMinorUnits', (t.amount_minor_units)::text, 'currency', t.currency, 'source', t.source, 'transactionDate', to_char((t.transaction_date)::timestamp with time zone, 'YYYY-MM-DD'::text), 'createdAtMilliseconds', (t.created_at_ms)::text, 'notes', t.notes, 'paymentMethod', t.payment_method, 'hasEmailReceipt', t.has_email_receipt, 'legacySubtotalMinorUnits', (t.legacy_subtotal_minor_units)::text, 'legacyTaxRatePct', (t.legacy_tax_rate_pct)::text, 'category',
        CASE
            WHEN (c.id IS NULL) THEN NULL::jsonb
            ELSE jsonb_build_object('id', c.id, 'name', c.display_name, 'kind', c.kind, 'revision', (c.revision)::text)
        END, 'receipt', r.payload, 'currentItemCategories', i.items) AS payload
   FROM (((public.spike_transactions t
     LEFT JOIN public.spike_budget_categories c ON (((c.account_id = t.account_id) AND (c.id = t.category_id))))
     LEFT JOIN ledger_private.transaction_receipt_display r ON (((r.account_id = t.account_id) AND (r.id = t.id))))
     LEFT JOIN ledger_private.transaction_current_item_categories i ON (((i.account_id = t.account_id) AND (i.id = t.id))));
